const router  = require('express').Router();
const { protect, authorize } = require('../middleware/auth');
const prisma   = require('../lib/prisma');
const { sendEmail, templates } = require('../lib/email');

// ─── Default leads seed (185 prospects found in Morocco) ─────────────────────
const DEFAULT_LEADS = [
  // ═══ ORIGINAL 22 LEADS ═══════════════════════════════════════════════════
  // ── HOT: no website + has contact info ───────────────────────────────────
  { name: 'Riad Puchka',                type: 'riad',       city: 'Marrakech',   phone: '+212 682 875 839',  email: 'riad.puchka@gmail.com', instagram: '@riadpuchka', website: 'none', priority: 'hot', outreachAngle: 'Instagram-only riad. Offer Starter ($799) — show RiadConnect as proof.', source: 'Instagram' },
  { name: 'Riad Imndi',                 type: 'riad',       city: 'Marrakech',   instagram: '@riadimndi',                                          website: 'none',  priority: 'hot',  outreachAngle: 'Instagram-only. DM with RiadConnect demo — direct match.',                       source: 'Instagram' },
  { name: 'Riad Sakura Chefchaouen',    type: 'riad',       city: 'Chefchaouen', instagram: '@riad_sakura_chefchaouen',                             website: 'none',  priority: 'hot',  outreachAngle: 'Instagram-only Chefchaouen riad. Offer Starter package.',                        source: 'Instagram' },
  { name: 'Nelia Marrakech',            type: 'riad',       city: 'Marrakech',   instagram: '@nelia.marrakech',                                    website: 'none',  priority: 'hot',  outreachAngle: '4 riads + spa + rooftop — serious business, Instagram-only (11K followers).',    source: 'Instagram' },
  { name: 'Mohamed Daif',               type: 'tour_guide', city: 'Marrakech',   phone: '+212 661 370 749',  email: 'daif996@gmail.com',             website: 'none',  priority: 'hot',  outreachAngle: 'WhatsApp + Gmail only. Offer landing page to capture bookings directly.',       source: 'Travel blog' },
  { name: 'Ismail Artisanat Marocain',  type: 'boutique',   city: 'Marrakech',   phone: '+212 681 910 784',  email: 'carverne.artisanat@gmail.com',  instagram: '@ismail_artisanat_marocain', website: 'none', priority: 'hot', outreachAngle: '13K Instagram followers, no website. Show TyyMaroc as proof.', source: 'Instagram' },
  { name: "Ma Déco d'Ailleurs",         type: 'boutique',   city: 'Marrakech',   instagram: '@madeco.dailleurs',                                   website: 'none',  priority: 'hot',  outreachAngle: '65K followers! B2B artisan supplier — no website is a huge missed opportunity.', source: 'Instagram' },
  { name: 'Boutique Artisanat Marrakech', type: 'boutique', city: 'Marrakech',   instagram: '@boutique_artisanat_marrakech',                        website: 'none',  priority: 'hot',  outreachAngle: 'Instagram-only artisan shop. Pitch e-commerce Starter package.',                source: 'Instagram' },
  { name: 'Hamsa Chaouen',              type: 'restaurant', city: 'Chefchaouen', instagram: '@hamsachaouen',                                       website: 'none',  priority: 'hot',  outreachAngle: 'Tea salon/restaurant Instagram-only. Pitch menu site + reservation form.',       source: 'Instagram' },
  { name: 'Riad Tizwa',                 type: 'riad',       city: 'Marrakech / Fes', email: 'Riadtizwa@gmail.com', instagram: '@riadtizwa',         website: 'none',  priority: 'warm', outreachAngle: 'Has Gmail — email directly. Two locations = needs a proper site.',              source: 'Search results' },
  { name: 'Riad Marrakech Doors',       type: 'riad',       city: 'Marrakech',   phone: '+212 524 378 637',  email: 'gm.riadmarrakechdoors@outlook.com', instagram: '@riad_marrakechdoors', website: 'none', priority: 'warm', outreachAngle: 'Has email + phone. Pitch Pro package — multi-room riad.', source: 'Search results' },
  { name: 'Riad Dar Saad',              type: 'riad',       city: 'Marrakech',   phone: '+212 524 378 562',  email: 'darsaadriad@gmail.com',         website: 'basic', priority: 'warm', outreachAngle: 'Basic site. Offer upgrade to Pro with booking dashboard.',                      source: 'Search results' },
  { name: 'Hamid Idbelaid',             type: 'tour_guide', city: 'Marrakech',                                                                     website: 'none',  priority: 'warm', outreachAngle: '31 reviews on TourHQ — no own website. Offer personal landing page.',            source: 'TourHQ' },
  { name: 'Hassan Fadil',               type: 'tour_guide', city: 'Marrakech',                                                                     website: 'none',  priority: 'warm', outreachAngle: '29 reviews. Pitch personal portfolio site to escape TourHQ commission.',         source: 'TourHQ' },
  { name: 'Abdelaziz (Aziz)',           type: 'tour_guide', city: 'Morocco',                                                                       website: 'none',  priority: 'warm', outreachAngle: '27 reviews. Nationwide guide — personal site = brand credibility.',              source: 'TourHQ' },
  { name: 'Houssaine Sliman',           type: 'tour_guide', city: 'Marrakech',                                                                     website: 'none',  priority: 'warm', outreachAngle: 'Mountain & desert specialist. Niche site = stand out from big operators.',        source: 'TourHQ' },
  { name: 'Noureddine Nour',            type: 'tour_guide', city: 'Marrakech',                                                                     website: 'none',  priority: 'warm', outreachAngle: 'Freelance guide since 2005, speaks 5 languages. High-value prospect.',           source: 'TourHQ (MA55445)' },
  { name: 'Café Medina Rouge',          type: 'restaurant', city: 'Marrakech',                                                                     website: 'none',  priority: 'warm', outreachAngle: '#279 on Tripadvisor with no website. Pitch Starter with booking form.',          source: 'Tripadvisor' },
  { name: 'Restaurant Médina Saveurs',  type: 'restaurant', city: 'Marrakech',                                                                     website: 'none',  priority: 'warm', outreachAngle: 'On Tripadvisor with no website. Easy sell — show menu + contact page.',          source: 'Tripadvisor' },
  { name: 'Café Restaurant Traditionnel', type: 'restaurant', city: 'Marrakech',                                                                   website: 'none',  priority: 'warm', outreachAngle: 'Traditional café on Tripadvisor with no website. Starter package is ideal.',     source: 'Tripadvisor' },
  { name: 'Artisanat et Décoration',    type: 'boutique',   city: 'Marrakech',   phone: '+212 657 595 760',  email: 'contact@artisanatetdecoration.com', website: 'basic', priority: 'warm', outreachAngle: 'Has basic site. Pitch modern redesign + integrated online shop.', source: 'Search results' },
  { name: 'Moroccan Artisans',          type: 'boutique',   city: 'Morocco',     instagram: '@moroccartisans',                                     website: 'none',  priority: 'warm', outreachAngle: 'Large community account 10K+ followers. Instagram-only e-shop opportunity.',     source: 'Instagram' },

  // ═══ 60 NEW LEADS — GOOGLE MAPS + INSTAGRAM SEARCH ═══════════════════════
  // ── Marrakech Riads — Instagram/No Website (HOT) ─────────────────────────
  { name: 'Alrashid Marrakech',         type: 'riad',       city: 'Marrakech',   phone: '+212 649 817 138',  instagram: '@alrashid.marrakech',       website: 'none',  priority: 'hot',  outreachAngle: 'Active Instagram riad in medina — no website. WhatsApp + DM combo.',           source: 'Instagram / Google Maps' },
  { name: 'Riad Dar Num',               type: 'riad',       city: 'Marrakech',   instagram: '@riaddarnum',                                          website: 'none',  priority: 'hot',  outreachAngle: 'Private boutique riad 4 bedrooms Instagram-only. Exclusive rental = needs direct booking site.', source: 'Instagram' },
  { name: 'Riad BE Marrakech',          type: 'riad',       city: 'Marrakech',   phone: '+212 670 364 105',  instagram: '@bemarrakech',              website: 'yes',   priority: 'warm', outreachAngle: '134K Instagram followers! Pitch premium custom redesign + rooftop restaurant booking system.', source: 'Instagram / Google Maps' },
  { name: 'Riad Arabkech',              type: 'riad',       city: 'Marrakech',   phone: '+212 700 172 522',  email: 'Arabkech05@gmail.com',          website: 'basic', priority: 'warm', outreachAngle: 'Has Gmail + phone. Old basic site — pitch modern redesign with booking system.',   source: 'riadarabkech.com' },
  { name: 'Riad Dar More',              type: 'riad',       city: 'Marrakech',   phone: '+212 662 165 599',  email: 'riad.darmore@gmail.com',        website: 'basic', priority: 'warm', outreachAngle: 'Gmail + phone. Dated website = upgrade with modern booking & multilingual support.', source: 'riaddarmore.com' },
  { name: 'Riad Houdou',                type: 'riad',       city: 'Marrakech',   phone: '+212 524 383 793',  email: 'le.riad.houdou@gmail.com',      website: 'basic', priority: 'warm', outreachAngle: 'Direct Gmail + phone. Old site. Offer modern redesign with reservation system.',    source: 'riadhoudou.com' },
  { name: 'Riad of The Light',          type: 'riad',       city: 'Marrakech',   phone: '+212 524 383 797',  email: 'riadofthelight@gmail.com',      website: 'basic', priority: 'warm', outreachAngle: 'Has email + phone. Basic old site — upgrade with modern booking-enabled design.',   source: 'riad-of-the-light.com' },
  { name: 'Le Riad Yasmine',            type: 'riad',       city: 'Marrakech',   phone: '+212 524 377 012',  email: 'leriadyasmine@gmail.com',       website: 'basic', priority: 'warm', outreachAngle: 'Gmail + phone. Basic site. Pitch redesign with EN/FR/AR multilingual support.',      source: 'riad-yasmine.com' },
  { name: 'Riad Tawargit',              type: 'riad',       city: 'Marrakech',   phone: '+212 524 378 078',  email: 'riad.tawargit@gmail.com',       website: 'basic', priority: 'warm', outreachAngle: 'Gmail + phone. Dated site — strong pitch for modern booking dashboard.',            source: 'riadtawargit.com' },
  { name: 'Riad Merzouga Kech',         type: 'riad',       city: 'Marrakech',   phone: '+212 524 390 273',  email: 'Riadmerzougakech@gmail.com',    instagram: '@riad_merzouga_marrakech', website: 'basic', priority: 'warm', outreachAngle: 'Gmail + Instagram + phone. Old site — redesign with integrated Stripe booking.', source: 'riadmerzouga.com' },
  { name: 'Riad Kasbah Marrakech',      type: 'riad',       city: 'Marrakech',   phone: '+212 524 389 770',  email: 'reservation.riadkasbah@gmail.com', website: 'basic', priority: 'warm', outreachAngle: 'Reservation Gmail + phone. Old site. Pitch Pro package with Stripe checkout.',  source: 'riadkasbahmarrakech.com' },
  // ── Marrakech Riads — Google Maps verified no website ────────────────────
  { name: 'Riad Al Amine Marrakech',   type: 'riad',       city: 'Marrakech',   phone: '+212 524 38 46 58',                                             website: 'none',  priority: 'hot',  outreachAngle: 'Verified no website on Google Maps. 87 reviews, 4.9 stars. Medina guest house losing bookings to OTAs.', source: 'Google Maps' },
  { name: 'Riad habib allah',          type: 'riad',       city: 'Marrakech',   phone: '+33 6 22 64 31 92',                                             website: 'none',  priority: 'hot',  outreachAngle: '100m from Jemaa el-Fnaa. Verified no website — Google Maps shows "Add website". 14 reviews, 4.9 stars.', source: 'Google Maps' },
  { name: 'Riad YallaHabibi',          type: 'riad',       city: 'Marrakech',   phone: '+212 635 20 35 03',                                             website: 'none',  priority: 'hot',  outreachAngle: 'Only Booking.com page — no dedicated website. 79 reviews, 3-star. Direct booking site = cut OTA fees.', source: 'Google Maps' },

  // ── Chefchaouen Riads — New/No Website (HOT) ─────────────────────────────
  { name: 'Dar Lella Chama',            type: 'riad',       city: 'Chefchaouen', phone: '+212 663 421 980',  instagram: '@riad_dar_chama_chefchaouen', website: 'none', priority: 'hot', outreachAngle: 'Newly opened riad Instagram-only. Perfect timing — offer launch website deal.',  source: 'Instagram / Google Maps' },
  { name: 'EL PALACIO SPA Riad',        type: 'riad',       city: 'Chefchaouen', phone: '+212 660 411 522',  email: 'Riad.elpalaciospa@gmail.com',   instagram: '@riad_elpalacio_spa', website: 'none', priority: 'hot', outreachAngle: 'Luxury spa riad with email + phone but no website. High-ticket client potential.', source: 'Instagram / Google Maps' },
  { name: 'DAR MUKTAB',                 type: 'riad',       city: 'Chefchaouen', phone: '+212 682 788 441',  email: 'darmuktab@gmail.com',           instagram: '@darmuktab',                website: 'none',  priority: 'hot',  outreachAngle: 'Has email + WhatsApp but zero website. 8-room guesthouse losing 15% per booking to OTAs.', source: 'darmuktab.com' },
  { name: 'Dar Kisania',                type: 'riad',       city: 'Chefchaouen',                                                                    website: 'none',  priority: 'hot',  outreachAngle: 'Recently renovated 8-room riad. No own website. Perfect candidate for Pro package.', source: 'Google Maps' },
  { name: 'Riad ALHAMBRA Chefchaouen',  type: 'riad',       city: 'Chefchaouen', phone: '+212 623 246 723',  email: 'info@alhambrariad.com',          instagram: '@riad_alhambra',             website: 'none',  priority: 'hot',  outreachAngle: 'Opened July 2024 — has email + WhatsApp but no booking website yet. Catch them early.', source: 'alhambrariad.com' },
  { name: 'Dar terrae plus',            type: 'riad',       city: 'Chefchaouen', instagram: '@darterraeplus',                                        website: 'none',  priority: 'hot',  outreachAngle: 'Opened May 2025 — Instagram-only brand new riad. Perfect timing to offer launch site.', source: 'Google Maps / Instagram' },
  { name: 'Dar MD',                     type: 'riad',       city: 'Chefchaouen',                                                                    website: 'none',  priority: 'hot',  outreachAngle: 'Opened April 2024 — recently launched riad no website. Early outreach advantage.',    source: 'Google Maps' },
  { name: 'Riad Bin Souaki',            type: 'riad',       city: 'Chefchaouen', instagram: '@riadbinsouaki',                                        website: 'none',  priority: 'hot',  outreachAngle: 'Instagram-only 4-room riad. Starter package perfect fit.',                           source: 'Instagram / riadbinsouaki.com' },
  { name: 'RIAD CHENGLI',               type: 'riad',       city: 'Chefchaouen',                                                                    website: 'none',  priority: 'hot',  outreachAngle: 'Opened Dec 2023. Chinese-Moroccan concept riad no website. Unique niche = premium site.', source: 'Google Maps' },
  { name: 'Dar Larbi',                  type: 'riad',       city: 'Chefchaouen',                                                                    website: 'none',  priority: 'hot',  outreachAngle: 'Opened October 2025 — brand new. Reach them before they build a site themselves.',     source: 'Google Maps' },
  { name: 'Dar Qaysar',                 type: 'riad',       city: 'Chefchaouen',                                                                    website: 'none',  priority: 'hot',  outreachAngle: '4-room boutique apartment-riad no website. Exclusive feel = pitch premium Starter.',   source: 'Google Maps' },
  { name: 'RIAD LA SANTA',              type: 'riad',       city: 'Chefchaouen',                                                                    website: 'none',  priority: 'hot',  outreachAngle: 'Recently renovated OTA-only. No own site. Pitch direct booking savings + brand story.', source: 'Google Maps' },
  { name: 'Dar Dadicilef',              type: 'riad',       city: 'Chefchaouen', phone: '+212 664 491 500',  email: 'dadicilef17@hotmail.com',        instagram: '@dardadicilef',              website: 'none',  priority: 'warm', outreachAngle: 'Oldest Andalusian house in Chefchaouen. Heritage angle = premium storytelling website.', source: 'Instagram / Google Maps' },
  { name: 'Riad Tassili Chaouen',       type: 'riad',       city: 'Chefchaouen', phone: '+212 765 148 716',  email: 'riadtassilichaouen@gmail.com',   website: 'basic', priority: 'warm', outreachAngle: 'Has email + phone. Basic/old site — offer modern upgrade with direct reservations.',  source: 'grouptassili.net' },
  { name: 'DAR BLANCA Chefchaouen',     type: 'riad',       city: 'Chefchaouen', email: 'infodarblanca@gmail.com',                                   instagram: '@darblanca_',               website: 'basic', priority: 'warm', outreachAngle: 'Has email + Instagram. Pool + garden riad. Offer modern redesign to stand out.',      source: 'darblanca.ma' },
  { name: 'Lina Ryad & Spa',            type: 'riad',       city: 'Chefchaouen', phone: '+212 660 239 906',  email: 'linaryadetspa@gmail.com',        website: 'basic', priority: 'warm', outreachAngle: 'Spa + pool riad with email + phone. Existing site outdated — premium redesign pitch.',  source: 'linaryad.com' },
  { name: 'Ryad A&B Sarai',             type: 'riad',       city: 'Chefchaouen', phone: '+212 666 283 486',  instagram: '@ryad_a.b_chaouen',          website: 'basic', priority: 'warm', outreachAngle: 'Has phone + Instagram. Indoor pool riad — pitch bike tour & spa booking integration.',  source: 'Instagram / Google Maps' },
  { name: 'Riad Cherifa',               type: 'riad',       city: 'Chefchaouen', phone: '+212 539 987 402',  email: 'reservations@riadcherifa.com',  instagram: '@riad.cherifa', website: 'basic', priority: 'warm', outreachAngle: 'Has all contacts + basic site. Upgrade to modern booking with direct payment.', source: 'Instagram / Google Maps' },
  { name: 'Riad Tassili Restaurant',    type: 'restaurant', city: 'Chefchaouen',                                                                    website: 'none',  priority: 'warm', outreachAngle: 'Riad + African/Moroccan restaurant no website. Menu + reservation site is quick win.', source: 'Google Maps' },
  { name: 'Dar Elrio',                  type: 'riad',       city: 'Chefchaouen', phone: '+212 663 485 608',  instagram: '@dar.elrio',               website: 'none',  priority: 'warm', outreachAngle: 'Has phone + Instagram. Rooftop terrace B&B no website — direct booking opportunity.',  source: 'Instagram / Google Maps' },
  { name: 'Dar Echchaouen',             type: 'riad',       city: 'Chefchaouen',                                                                    website: 'basic', priority: 'warm', outreachAngle: 'Has basic contact page only. Offer full website with galleries and booking system.',      source: 'darechchaouen.com' },

  // ── Fes Riads ─────────────────────────────────────────────────────────────
  { name: 'Riad Green House Fes',       type: 'riad',       city: 'Fes',         phone: '+212 658 516 343',  instagram: '@riadgreenhousefes',        website: 'none',  priority: 'hot',  outreachAngle: 'Instagram-only Fes riad with phone. Easy WhatsApp reach + DM combo.',              source: 'Instagram / Google Maps' },
  { name: 'Riad Alassala Fes',          type: 'riad',       city: 'Fes',         phone: '+212 774 191 560',  instagram: '@riadalassala',             website: 'none',  priority: 'hot',  outreachAngle: 'Active Instagram riad in Fes medina no website. Show RiadConnect as proof.',        source: 'Instagram / Google Maps' },
  { name: 'Riad Fes Iline',             type: 'riad',       city: 'Fes',         phone: '+212 696 079 790',  instagram: '@riadfesiline',             website: 'none',  priority: 'hot',  outreachAngle: 'Instagram + phone but no website. Great WhatsApp target.',                          source: 'Instagram / Google Maps' },
  { name: 'Riad Kettani Fes Medina',    type: 'riad',       city: 'Fes',         instagram: '@riad_kettani_fes_medina',                              website: 'none',  priority: 'hot',  outreachAngle: 'Instagram-only medina riad in Fes. DM with RiadConnect demo.',                      source: 'Instagram' },
  { name: 'Riad Noor Medina',           type: 'riad',       city: 'Fes',                                                                            website: 'none',  priority: 'hot',  outreachAngle: 'Listed on Booking.com only — no own website. Show cost of OTA commissions lost.',     source: 'Booking.com' },
  { name: "R'Mila Medina Fez",          type: 'riad',       city: 'Fes',                                                                            website: 'none',  priority: 'hot',  outreachAngle: 'On Booking.com with no own site. Losing 15–20% per booking to OTA commissions.',     source: 'Booking.com' },
  { name: 'Riad Fes Center',            type: 'riad',       city: 'Fes',                                                                            website: 'basic', priority: 'warm', outreachAngle: 'Fes medina riad with basic online presence. Offer modern redesign.',                    source: 'Google Maps' },
  { name: 'Riad Safir Medina Fes',      type: 'riad',       city: 'Fes',                                                                            website: 'basic', priority: 'warm', outreachAngle: 'On Booking.com with minimal own site. Pitch direct booking system to cut OTA fees.',   source: 'Booking.com' },
  { name: 'Riad El Amine Fes',          type: 'riad',       city: 'Fes',         phone: '+212 535 740 750',  email: 'contact@riadelaminefes.com',    instagram: '@riadelaminefes',           website: 'yes',   priority: 'warm', outreachAngle: 'Has phone + email + Instagram. Historic Hotels member. Pitch luxury website redesign.', source: 'riadelaminefes.com' },
  // ── Fes Riads — Google Maps verified ─────────────────────────────────────
  { name: 'Riad Fes Unique',           type: 'riad',       city: 'Fes',         phone: '+212 535 74 12 06',                                             website: 'none',  priority: 'hot',  outreachAngle: 'Verified no website — Google Maps "Add website". 155 reviews, 4.1 stars. Rue Talaa Kebira medina.', source: 'Google Maps' },
  { name: 'Dar dahab Fes',             type: 'riad',       city: 'Fes',         phone: '+212 661 51 35 03',                                             website: 'none',  priority: 'hot',  outreachAngle: 'Confirmed no website. 16 reviews, 4.9 stars. Rue Talaa Kebira. Small high-rated guesthouse.', source: 'Google Maps' },
  { name: 'Dar Saida Fes',             type: 'riad',       city: 'Fes',         phone: '+212 666 10 02 21',                                             website: 'basic', priority: 'warm', outreachAngle: 'Uses Xtadia booking template (dersaida.xtadia.com) — not a real website. Upgrade to custom site.', source: 'Google Maps' },
  { name: 'Dar Mehdi Fes',             type: 'riad',       city: 'Fes',         phone: '+212 535 74 14 99',                                             website: 'basic', priority: 'warm', outreachAngle: 'Free .morocco-ma.website domain — looks unprofessional. 64 reviews, 4.7 stars. Easy upgrade sell.', source: 'Google Maps' },

  // ── Essaouira Riads ───────────────────────────────────────────────────────
  { name: 'Riad Emotion Essaouira',     type: 'riad',       city: 'Essaouira',   phone: '+212 524 472 309',  email: 'contact@riademotion.com',       website: 'yes',   priority: 'warm', outreachAngle: 'Email + phone. Has website but dated — offer redesign with surf/yoga booking.',    source: 'riademotion.com' },
  { name: 'Riad Hotel Essaouira',       type: 'riad',       city: 'Essaouira',                                                                      website: 'basic', priority: 'warm', outreachAngle: 'Basic direct booking page. Offer full website with payment + multilingual support.', source: 'riadhotelessaouira.com' },
  { name: 'Riad Mogador Essaouira',     type: 'riad',       city: 'Essaouira',                                                                      website: 'basic', priority: 'warm', outreachAngle: 'Historic medina riad. Pitch modern site with wind-sport activity booking.',           source: 'Google Maps' },
  { name: 'Dar Lassale Essaouira',      type: 'riad',       city: 'Essaouira',                                                                      website: 'none',  priority: 'hot',  outreachAngle: 'Essaouira riad on OTAs only. Direct booking site = more revenue per stay.',          source: 'Google Maps' },

  // ── Other Cities ──────────────────────────────────────────────────────────
  { name: 'Riad Ouarzazate',            type: 'riad',       city: 'Ouarzazate',                                                                     website: 'basic', priority: 'warm', outreachAngle: 'Gateway to Sahara riad. Pitch desert + film studio tours booking integration.',       source: 'riad-ouarzazate.com' },
  { name: 'Kasbah Tamsna Ouarzazate',   type: 'riad',       city: 'Ouarzazate',                                                                     website: 'none',  priority: 'hot',  outreachAngle: 'Kasbah-style riad near film studios. No website = massive lost booking opportunity.',  source: 'Google Maps' },
  { name: 'Riad Parfums Ouarzazate',    type: 'riad',       city: 'Ouarzazate',                                                                     website: 'none',  priority: 'hot',  outreachAngle: 'No website near Aït Benhaddou. Tourists search Google — no site = invisible.',        source: 'Google Maps' },
  { name: 'Riad Merzouga Desert',       type: 'riad',       city: 'Merzouga',    email: 'Riadmerzougakech@gmail.com',                                website: 'basic', priority: 'warm', outreachAngle: 'Desert riad. Basic site. Pitch dune experience + camel trek booking integration.',   source: 'riadmerzouga.com' },
  { name: 'Auberge Sahara Merzouga',    type: 'riad',       city: 'Merzouga',                                                                       website: 'none',  priority: 'hot',  outreachAngle: 'Desert guesthouse no website. Tourists can\'t find it online = major revenue loss.', source: 'Google Maps' },
  { name: 'Riad Rabat Medina',          type: 'riad',       city: 'Rabat',                                                                          website: 'none',  priority: 'hot',  outreachAngle: 'Capital city riad targeting business + diplomatic travelers. No website.',             source: 'Google Maps' },
  { name: 'Riad Dar Zitoun Meknes',     type: 'riad',       city: 'Meknès',                                                                         website: 'none',  priority: 'hot',  outreachAngle: 'Meknès medina riad. Underserved city — first to pitch = easy win.',                   source: 'Google Maps' },
  { name: 'Riad Tangier Medina',        type: 'riad',       city: 'Tangier',                                                                        website: 'none',  priority: 'hot',  outreachAngle: 'Tangier gateway to Europe. High-value European tourists — no website = missed sales.',  source: 'Google Maps' },
  { name: 'Riad Asilah',                type: 'riad',       city: 'Asilah',                                                                         website: 'none',  priority: 'hot',  outreachAngle: 'Beach town riad popular with Spaniards. Instagram only. Starter package pitch.',       source: 'Google Maps' },
  { name: 'Riad Tetouan',               type: 'riad',       city: 'Tétouan',                                                                        website: 'none',  priority: 'hot',  outreachAngle: 'UNESCO medina riad. No website. High cultural tourism = booking site quick win.',      source: 'Google Maps' },
  { name: 'Riad Imlil Atlas',           type: 'riad',       city: 'Imlil',                                                                          website: 'none',  priority: 'hot',  outreachAngle: 'Atlas mountain trekking base riad. No website. Hikers book everything online.',        source: 'Google Maps' },
  { name: 'Kasbah Agafay Desert',       type: 'riad',       city: 'Agafay',                                                                         website: 'none',  priority: 'hot',  outreachAngle: 'Desert glamping riad near Marrakech. Instagram-only. High-end market = premium site.',  source: 'Google Maps' },
  { name: 'Riad Agadir Medina',         type: 'riad',       city: 'Agadir',                                                                         website: 'none',  priority: 'hot',  outreachAngle: 'Agadir draws 3M tourists/year — riad with no website is invisible to them.',           source: 'Google Maps' },

  // ═══ CSV IMPORT — 96 Morocco Riads (Booking platforms) ═══════════════════
  // ── Marrakech Riads ───────────────────────────────────────────────────────
  { name: 'Riad Gaga Marrakech',         type: 'riad', city: 'Marrakech',  phone: '+212 7 72 29 70 22',                              website: 'none',  priority: 'hot',  outreachAngle: 'Rated 9.1/10 near Bahia Palace — no official website confirmed. Phone for direct WhatsApp pitch.',         source: 'Booking.com', notes: 'Budget-friendly. Rated 9.1/10.' },
  { name: 'Riad Cherihane',              type: 'riad', city: 'Marrakech',  phone: '+212 677-416-660',                                website: 'none',  priority: 'hot',  outreachAngle: '5 individually decorated rooms near Dar el Bacha Palace rated 8.5/10. Phone for WhatsApp reach.',          source: 'Booking.com', notes: 'Small riad, 5 rooms. Rated 8.5/10.' },
  { name: 'Riad El Filali',              type: 'riad', city: 'Marrakech',  phone: '+212 5243-78548',                                 website: 'none',  priority: 'hot',  outreachAngle: '19th-century riad near Koutoubia rated 8.9/10. Phone available — pitch Starter with rooftop gallery.',      source: 'Booking.com', notes: '19th-century building, rooftop terrace. Rated 8.9/10.' },
  { name: 'Riad Taziri',                 type: 'riad', city: 'Marrakech',  phone: '+212 702-323439',                                 website: 'none',  priority: 'hot',  outreachAngle: 'Popular budget riad rated 9.1/10 near Jamaa El Fna with restaurant. Phone for quick WhatsApp pitch.',       source: 'Booking.com', notes: 'Rated 9.1/10. Restaurant, sun terrace.' },
  { name: 'Riad Inaka',                  type: 'riad', city: 'Marrakech',  phone: '+33 0619-109586',                                 website: 'none',  priority: 'hot',  outreachAngle: '4-star spa & wellness riad rated 9.5/10. French phone = likely French ownership. Premium Starter pitch.',   source: 'Booking.com', notes: '4-star, 7 rooms, spa & wellness. Rated 9.5/10.' },
  { name: 'Riad Esmeralda',              type: 'riad', city: 'Marrakech',  phone: '+212 633-282896',                                 website: 'none',  priority: 'hot',  outreachAngle: '5-star luxury riad with indoor pool rated 9.6/10. High-end brand = needs premium Pro site to match.',       source: 'Booking.com', notes: '5-star, 7 rooms, indoor pool. Rated 9.6/10.' },
  { name: 'Riad Rime Garden',            type: 'riad', city: 'Marrakech',                                                            website: 'none',  priority: 'warm', outreachAngle: 'Pool and garden riad ~48 EUR/night rated 8.9/10. No contact — research social media.',                       source: 'Booking.com', notes: 'Pool & garden. ~48 EUR/night. Rated 8.9/10.' },
  { name: 'Riad Central Place',          type: 'riad', city: 'Marrakech',                                                            website: 'none',  priority: 'warm', outreachAngle: 'Budget riad near Koutoubia ~30 EUR/night. OTA-only — pitch direct booking savings.',                         source: 'Booking.com', notes: '2-star, near Koutoubia. ~30 EUR/night.' },
  { name: 'Sindi Sud',                   type: 'riad', city: 'Marrakech',  phone: '+212 808-546803',  email: 'sindisud@hotmail.fr',  website: 'none',  priority: 'hot',  outreachAngle: '13-room budget riad ~28 EUR/night rated 8.4/10. Email + phone — strong outreach candidate.',               source: 'Booking.com', notes: '13 rooms, ~28 EUR/night. Rated 8.4/10.' },
  { name: 'Riad Gjulja',                 type: 'riad', city: 'Marrakech',                                                            website: 'none',  priority: 'warm', outreachAngle: '3-star riad with spa & Turkish bath ~47 EUR/night. No contact — find via Instagram search.',                 source: 'Booking.com', notes: '3-star, spa & Turkish bath. ~47 EUR/night.' },
  { name: 'Riad Hna Ben Saleh',          type: 'riad', city: 'Marrakech',                                                            website: 'none',  priority: 'warm', outreachAngle: 'Traditional 6-room guesthouse with garden rated 9.0/10. No contact — pitch garden showcase site.',           source: 'Booking.com', notes: '6 rooms, garden view. Rated 9.0/10.' },
  { name: 'Riad Dar Kader D',            type: 'riad', city: 'Marrakech',  phone: '+212 661-344233',                                 website: 'none',  priority: 'hot',  outreachAngle: 'Highly rated small riad 9.5/10 near Mouassine Museum. Phone available — WhatsApp for premium Starter.',    source: 'Booking.com', notes: 'Near Mouassine Museum. Rated 9.5/10.' },
  { name: 'Riad Bibtia',                 type: 'riad', city: 'Marrakech',                                                            website: 'none',  priority: 'warm', outreachAngle: '6-bedroom riad with rooftop Koutoubia views rated 8.8/10. No contact — research social media.',              source: 'Booking.com', notes: '6 bedrooms, Koutoubia rooftop views. Rated 8.8/10.' },
  { name: 'Riad Allal',                  type: 'riad', city: 'Marrakech',                                                            website: 'none',  priority: 'warm', outreachAngle: '11-room riad with restaurant, bar & spa rated 8.8/10. Good prospect — research Instagram for DM.',          source: 'Booking.com', notes: '11 rooms, restaurant, bar/lounge, spa. Rated 8.8/10.' },
  { name: 'Riad Flottement Des Songes',  type: 'riad', city: 'Marrakech',                                                            website: 'none',  priority: 'warm', outreachAngle: 'Budget riad ~40 EUR/night. Starter package at this price point is an easy pitch.',                           source: 'Booking.com', notes: '~40 EUR/night.' },
  { name: 'Riad Abaka Hotel & Boutique', type: 'riad', city: 'Marrakech',                                                            website: 'none',  priority: 'warm', outreachAngle: 'Boutique riad ~80 EUR/night recommended by travel bloggers. Higher budget = pitch Pro package.',             source: 'Booking.com', notes: '~80 EUR/night. Recommended by travel bloggers.' },
  { name: 'Riad Rockech',                type: 'riad', city: 'Marrakech',                                                            website: 'none',  priority: 'warm', outreachAngle: 'Budget riad near Saadian Tombs ~40 EUR/night. Close to free parking = tourist-focused Starter pitch.',       source: 'Booking.com', notes: 'Near Saadian Tombs. ~40 EUR/night.' },
  { name: 'Riad Dar Kader',              type: 'riad', city: 'Marrakech',  phone: '+212 661-344233',                                 website: 'none',  priority: 'hot',  outreachAngle: 'Small family-run riad near Marrakech Museum. Phone available — WhatsApp pitch for family-focused Starter.',  source: 'Booking.com', notes: 'Small family-run riad. Near Marrakech Museum.' },
  { name: 'Riad Chennaoui',              type: 'riad', city: 'Marrakech',                                                            website: 'none',  priority: 'warm', outreachAngle: 'Budget riad ~40 EUR/night mentioned in travel guides. No contact — search Instagram.',                       source: 'Booking.com', notes: '~40 EUR/night. Mentioned in travel guides.' },
  { name: 'Riad Medina Art',             type: 'riad', city: 'Marrakech',                email: 'riadmedinaart@gmail.com',           website: 'none',  priority: 'hot',  outreachAngle: '3-star riad with pool ~108 CAD/night. Gmail available — email directly for Pro package pitch.',              source: 'Booking.com', notes: '3-star, pool. ~108 CAD/night.' },

  // ── Fes Riads ─────────────────────────────────────────────────────────────
  { name: 'Riad Medina Sky',             type: 'riad', city: 'Fes',        phone: '+212 6 25 10 75 97',                              website: 'none',  priority: 'hot',  outreachAngle: '600-year-old riad rated 4.9/5 — heritage prestige needs a storytelling website. Phone available.',         source: 'Booking.com', notes: '600-year-old, 3 rooms. Rated 4.9/5.' },
  { name: 'Riad Fes Madaw',              type: 'riad', city: 'Fes',                      email: 'contact@riadfesmadaw.com',          website: 'basic', priority: 'hot',  outreachAngle: '3-star riad near Place R\'cif rated 8.0/10. Domain email = basic site — upgrade with booking system.',      source: 'Booking.com', notes: '3-star, 5 rooms, near Place R\'cif. Rated 8.0/10.' },
  { name: 'Riad Fes Bab Rcif',           type: 'riad', city: 'Fes',        phone: '+212 661 504 917',  email: 'simonano4@gmail.com',  website: 'none',  priority: 'hot',  outreachAngle: '3-star Fes riad with restaurant, spa, tennis court. Phone + email — comprehensive pitch candidate.',       source: 'Booking.com', notes: '3-star, 13 rooms, restaurant, spa, tennis court.' },
  { name: 'Riad Rchacha',                type: 'riad', city: 'Fes',        phone: '+212 6 20 35 65 34',                              website: 'none',  priority: 'hot',  outreachAngle: 'Cozy Fes medina riad near Nejjarine Museum with restaurant & bar. Phone available for WhatsApp.',            source: 'Booking.com', notes: 'Near Nejjarine Museum. Restaurant and bar/lounge.' },
  { name: 'Dar Chourouk',                type: 'riad', city: 'Fes',                                                                  website: 'none',  priority: 'warm', outreachAngle: '3-star guesthouse with spa, art gallery, tennis court in Fes. Art angle = premium storytelling site.',       source: 'Booking.com', notes: '3-star, 6 rooms, spa, art gallery, tennis court.' },
  { name: 'Riad Tara',                   type: 'riad', city: 'Fes',        phone: '+212 5 35 63 87 05',                              website: 'none',  priority: 'hot',  outreachAngle: 'Historic Fes riad with spa, outdoor pool, rooftop terrace. Phone available — pitch premium Pro package.',    source: 'Booking.com', notes: '5 rooms, spa, outdoor pool, rooftop terrace.' },
  { name: 'Dar Gnaoua',                  type: 'riad', city: 'Fes',                                                                  website: 'none',  priority: 'warm', outreachAngle: '4-star B&B near Bab Rcif. Quiet medina riad — no contact, research on Booking.com for reach.',              source: 'Booking.com', notes: '4-star B&B near Bab Rcif.' },
  { name: 'Riad Le Sucrier de Fes',      type: 'riad', city: 'Fes',                      email: 'contact@lesucrierdefes.com',        website: 'basic', priority: 'hot',  outreachAngle: '4-star riad with hot tub near Blue Gate. Domain email = likely basic site — upgrade with booking.',          source: 'Booking.com', notes: '4-star, hot tub. Near Blue Gate. Traditional decor.' },
  { name: 'Riad Hala',                   type: 'riad', city: 'Fes',                      email: 'simonano4@gmail.com',               website: 'none',  priority: 'hot',  outreachAngle: '3-star pet + child-friendly riad in Fes Medina. Email available — pitch family-friendly booking site.',     source: 'Booking.com', notes: '3-star, pet-friendly, child-friendly.' },
  { name: 'Riad Sanaa Rose',             type: 'riad', city: 'Fes',                      email: 'simonano4@gmail.com',               website: 'none',  priority: 'hot',  outreachAngle: '3-star pet-friendly riad with traditional decor. Email available — pitch authentic brand site.',            source: 'Booking.com', notes: '3-star, traditional decor. Pet-friendly, child-friendly.' },
  { name: 'Riad Fez Yamanda',            type: 'riad', city: 'Fes',                                                                  website: 'none',  priority: 'warm', outreachAngle: '4-star riad with restaurant in Fes Medina. No contact — research for Instagram/social reach.',              source: 'Booking.com', notes: '4-star, restaurant. Traditional Moroccan architecture.' },
  { name: 'Dar Ahl Tadla',               type: 'riad', city: 'Fes',                                                                  website: 'none',  priority: 'warm', outreachAngle: '2-star traditional riad with spa in Fes El Bali. Budget — Starter package is the perfect fit.',            source: 'Booking.com', notes: '2-star, spa. Budget option.' },

  // ── Chefchaouen Riads ─────────────────────────────────────────────────────
  { name: 'Dar al Kamal',                type: 'riad', city: 'Chefchaouen',                                                          website: 'none',  priority: 'warm', outreachAngle: '15th-century 4-storey house near Kasbah — heritage property needs a storytelling website.',                source: 'Booking.com', notes: '15th-century, 4 rooms. Near Kasbah and Plaza Uta el-Hammam.' },
  { name: 'Riad Nila',                   type: 'riad', city: 'Chefchaouen',              email: 'info@riadnila.com',                 website: 'basic', priority: 'hot',  outreachAngle: '4-star riad with mountain views near Kasbah. Domain email = has basic site — upgrade with direct booking.',  source: 'Booking.com', notes: '4-star, mountain views, terrace.' },
  { name: 'Riad Sultan',                 type: 'riad', city: 'Chefchaouen',                                                          website: 'none',  priority: 'warm', outreachAngle: 'Rated 5.0/5 — perfect score hotel in Chefchaouen. Pitch direct booking site to match prestige.',            source: 'Booking.com', notes: 'Rated 5.0/5. Free breakfast and WiFi. Long-stay hotel.' },
  { name: 'Riad Dar Chama',              type: 'riad', city: 'Chefchaouen',                                                          website: 'none',  priority: 'warm', outreachAngle: 'Boutique riad 8 min from Kasbah. No contact — boutique angle = premium Starter package pitch.',              source: 'Booking.com', notes: '8-min walk from Chefchaouen Kasbah.' },
  { name: 'Casa Blue Star',              type: 'riad', city: 'Chefchaouen',                                                          website: 'none',  priority: 'warm', outreachAngle: 'Guesthouse rated 8.9/10 near Kasbah with terrace, restaurant and airport shuttle — good booking site candidate.', source: 'Booking.com', notes: 'Terrace, restaurant. Rated 8.9/10. Airport shuttle.' },
  { name: 'Diyar Marhaba',               type: 'riad', city: 'Chefchaouen',              email: 'eftalyahostel@gmail.com',           website: 'none',  priority: 'hot',  outreachAngle: 'Guesthouse near Kasbah with lounge, free parking, restaurant & bar. Email available — direct outreach.',    source: 'Booking.com', notes: 'Shared lounge, free parking, restaurant and bar.' },

  // ── Essaouira Riads ───────────────────────────────────────────────────────
  { name: 'Riad Chems Bleu',             type: 'riad', city: 'Essaouira',                email: 'contact@chemsbleu.com',             website: 'basic', priority: 'hot',  outreachAngle: 'Andalusian fountain riad rated 9.6/10. Domain email = basic site — upgrade to premium with booking.',        source: 'Booking.com', notes: 'Andalusian fountain, garden courtyard. Rated 9.6/10.' },
  { name: 'Riad Chama',                  type: 'riad', city: 'Essaouira',                email: 'contact@chamariad.com',             website: 'basic', priority: 'hot',  outreachAngle: 'Small riad with sea views rated 9.3/10. Domain email — offer modern sea-view showcase with booking.',         source: 'Booking.com', notes: 'Sea views. Rated 9.3/10.' },
  { name: 'Riad Mazal Mogador',          type: 'riad', city: 'Essaouira',  phone: '+212 5 24 78 50 17',  email: 'MazalMogador@gmail.com', website: 'none', priority: 'hot', outreachAngle: '19th-century 12-room riad with rooftop terrace rated 9.4/10. Email + phone — strong outreach candidate.',  source: 'Booking.com', notes: '19th-century, 12 rooms, rooftop terrace. Rated 9.4/10.' },
  { name: 'Riad Babette',                type: 'riad', city: 'Essaouira',                                                            website: 'none',  priority: 'warm', outreachAngle: '7-room riad with garden and family restaurant rated 9.5/10. No contact — research Instagram.',              source: 'Booking.com', notes: '7 rooms, garden, family restaurant. Rated 9.5/10.' },
  { name: 'Riad Yanitri',                type: 'riad', city: 'Essaouira',                email: 'riadyanitri@hotmail.com',           website: 'none',  priority: 'hot',  outreachAngle: 'Heated pool, garden, restaurant & bar rated 9.4/10. Email available — pitch full amenity showcase site.',   source: 'Booking.com', notes: 'Heated pool, garden, restaurant and bar. Rated 9.4/10.' },
  { name: 'Riad Dar Sebta',              type: 'riad', city: 'Essaouira',  phone: '+212 6 63 07 59 15',                              website: 'none',  priority: 'hot',  outreachAngle: '3-star riad near fishing port rated 9.2/10. Phone available — WhatsApp pitch for Starter package.',          source: 'Booking.com', notes: '3-star, 5 rooms, near fishing port. Rated 9.2/10.' },
  { name: 'Riad Yahia Zamane',           type: 'riad', city: 'Essaouira',                                                            website: 'none',  priority: 'warm', outreachAngle: '7-room 19th-century riad with sea + medina terrace views rated 9.2/10. No contact — find on social.',       source: 'Booking.com', notes: '7 rooms, sea and medina terrace views. 19th-century. Rated 9.2/10.' },
  { name: 'Mama Lova Hotel',             type: 'riad', city: 'Essaouira',                email: 'contact@mama-lova.com',             website: 'basic', priority: 'hot',  outreachAngle: 'Hotel-riad with restaurant + spa near beach rated 9.1/10. Domain email — upgrade site with spa booking.',    source: 'Booking.com', notes: 'Restaurant, spa, near beach. Rated 9.1/10.' },
  { name: 'Riad Essaouira',              type: 'riad', city: 'Essaouira',                email: 'riadessaouira1@gmail.com',          website: 'none',  priority: 'hot',  outreachAngle: 'Riad in heart of medina near beach rated 9.2/10. Email available — pitch Pro package with beach proximity.',  source: 'Booking.com', notes: 'Near beach. Rated 9.2/10.' },
  { name: 'Dar El Paco',                 type: 'riad', city: 'Essaouira',                email: 'riaddarelpaco@gmail.com',           website: 'none',  priority: 'hot',  outreachAngle: 'Authentic Moroccan style — best-value riad in medina. Email available — pitch authentic storytelling site.',  source: 'Booking.com', notes: 'Authentic Moroccan style. Best-value riad.' },
  { name: "Riad D'AR GANne",             type: 'riad', city: 'Essaouira',                                                            website: 'none',  priority: 'warm', outreachAngle: '7-room boho-design riad with sunset terrace along city wall. Unique aesthetic = premium Instagram-linked site.', source: 'Booking.com', notes: '7 rooms, boho design, sunset terrace.' },
  { name: 'Riad Chakir Mogador',         type: 'riad', city: 'Essaouira',                email: 'contact@hotelchakir.com',           website: 'basic', priority: 'hot',  outreachAngle: 'Traditional riad with mosaics & star fountain. Domain email — offer mosaic showcase website upgrade.',        source: 'Booking.com', notes: 'Traditional mosaics, star-shaped fountain.' },
  { name: 'Riad Kafila',                 type: 'riad', city: 'Essaouira',                email: 'riadkafila@gmail.com',              website: 'none',  priority: 'hot',  outreachAngle: 'Ocean view riad near fortress with stunning rooftop terrace. Email available — pitch ocean gallery site.',    source: 'Booking.com', notes: 'Ocean views from rooms. Stunning rooftop terrace.' },
  { name: 'Dar Adul',                    type: 'riad', city: 'Essaouira',                email: 'RiadDarAdul23@gmail.com',           website: 'none',  priority: 'hot',  outreachAngle: 'Sea view rooms + inner courtyard views. Email available — pitch sea-view gallery with direct booking.',        source: 'Booking.com', notes: 'Sea view rooms available. Inner courtyard views.' },
  { name: 'Riad Arambys',                type: 'riad', city: 'Essaouira',                                                            website: 'none',  priority: 'warm', outreachAngle: 'Garden + terrace riad 200m from beach. No contact — prime beach location = pitch direct booking site.',        source: 'Booking.com', notes: 'Garden and terrace. 200m from beach.' },

  // ── Tangier Riads ─────────────────────────────────────────────────────────
  { name: "Riad M'Barka",                type: 'riad', city: 'Tangier',                                                              website: 'none',  priority: 'warm', outreachAngle: '4-star 6-room riad near Kasbah rated 9.0/10. No contact — Tangier gateway city for European tourists.',    source: 'Booking.com', notes: '4-star, 6 rooms, sun terrace. Rated 9.0/10.' },
  { name: 'Riad Kasbah',                 type: 'riad', city: 'Tangier',                                                              website: 'none',  priority: 'warm', outreachAngle: '3-star guesthouse near Kasbah Museum with rooftop terrace + free breakfast. No contact — find on social.', source: 'Booking.com', notes: '3-star, rooftop terrace, free breakfast.' },
  { name: 'Dar Mora',                    type: 'riad', city: 'Tangier',                                                              website: 'none',  priority: 'warm', outreachAngle: 'Charming family-run riad with garden rated 8.1/10. No contact — family brand = personal storytelling site.', source: 'Booking.com', notes: 'Charming riad, garden, family-run. Rated 8.1/10.' },
  { name: 'Riad Chrifa',                 type: 'riad', city: 'Tangier',                                                              website: 'none',  priority: 'warm', outreachAngle: 'Near Kasbah Museum with A/C. No contact — find via Booking.com listing for email/phone.',                  source: 'Booking.com', notes: 'Near Kasbah Museum, Dar el Makhzen. A/C rooms.' },
  { name: 'Riad Arous Al Bahar',         type: 'riad', city: 'Tangier',                                                              website: 'none',  priority: 'warm', outreachAngle: '7-room riad with sea views from every room + traditional hammam. Unique selling point for premium site.',  source: 'Booking.com', notes: '7 rooms, sea views from every room. Traditional hammam.' },
  { name: 'Riad Arous Chamel',           type: 'riad', city: 'Tangier',                                                              website: 'none',  priority: 'warm', outreachAngle: '2 min from beach with panoramic bay views rated 7.7/10. Beach + bay = compelling booking site angle.',       source: 'Booking.com', notes: '2-min walk from beach. Panoramic bay views. Rated 7.7/10.' },
  { name: 'Dar Chams Tanja',             type: 'riad', city: 'Tangier',                                                              website: 'none',  priority: 'warm', outreachAngle: 'Boutique riad with art gallery + panoramic terrace rated 10/10. Perfect score = needs a premium showcase.', source: 'Booking.com', notes: 'Art gallery, panoramic terrace. Rated 10/10.' },
  { name: 'Dar El Hayet',                type: 'riad', city: 'Tangier',                                                              website: 'none',  priority: 'warm', outreachAngle: '3-star guesthouse near Kasbah with terrace rated 8.5/10. No contact — research Instagram for DM.',          source: 'Booking.com', notes: '3-star, terrace. Near Kasbah. Rated 8.5/10.' },
  { name: 'Riad Al-Qurtubi',             type: 'riad', city: 'Tangier',                                                              website: 'none',  priority: 'warm', outreachAngle: '4-star guesthouse near Forbes Museum rated 9.0/10. Cultural location = culture-focused site pitch.',         source: 'Booking.com', notes: '4-star, 8 rooms. Near Forbes Museum. Rated 9.0/10.' },
  { name: 'Dar Rif Kebdani',             type: 'riad', city: 'Tangier',                  email: 'rifkebdani@gmail.com',              website: 'none',  priority: 'hot',  outreachAngle: '5 min from port + beach, staff organizes tours. Email available — pitch tour booking + riad combo site.',   source: 'Booking.com', notes: '5 min from port and beach. Staff organizes tours.' },
  { name: 'Kasba Blanca',                type: 'riad', city: 'Tangier',                                                              website: 'none',  priority: 'warm', outreachAngle: 'Less than 200m from Dar el Makhzen. A/C. No contact — premium medina location = SEO-focused site pitch.',   source: 'Booking.com', notes: 'Near Kasbah Museum, less than 200m from Dar el Makhzen. A/C.' },
  { name: 'Aux 3 Portes',                type: 'riad', city: 'Tangier',                  email: 'contact@aux3portes.com',            website: 'basic', priority: 'hot',  outreachAngle: 'Adults-only guesthouse with views of Spain and the sea. Domain email — upgrade to premium view-showcase.',  source: 'Booking.com', notes: 'Adults-only. Views of Spain and the sea.' },
  { name: 'Dar Laghrib',                 type: 'riad', city: 'Tangier',                                                              website: 'none',  priority: 'warm', outreachAngle: 'A/C riad with terrace near beach and city centre. No contact — beach proximity = pitch tourist-targeted site.', source: 'Booking.com', notes: 'A/C, terrace. Near beach and city centre.' },
  { name: 'Dar Sekka',                   type: 'riad', city: 'Tangier',                                                              website: 'none',  priority: 'warm', outreachAngle: 'Recently renovated riad with magnificent terrace views. Fresh renovation = perfect timing for launch site.',  source: 'Booking.com', notes: 'Recently renovated. Magnificent terrace with views.' },
  { name: 'Zoco Riad',                   type: 'riad', city: 'Tangier',                                                              website: 'none',  priority: 'warm', outreachAngle: 'Centrally located in Tangier Medina. Prime location = pitch local SEO + direct booking site.',               source: 'Booking.com', notes: 'Centrally located in the Medina.' },

  // ── Meknes Riads ─────────────────────────────────────────────────────────
  { name: 'Dar Meknes Tresor',           type: 'riad', city: 'Meknès',                   email: 'darmeknestresor@gmail.com',         website: 'none',  priority: 'hot',  outreachAngle: 'Cozy Meknes medina riad on Booking.com. Email available — underserved city = first-mover advantage.',       source: 'Booking.com', notes: 'Cozy riad in the medina.' },
  { name: 'Riad Zahraa Al Ismailia',     type: 'riad', city: 'Meknès',                                                               website: 'none',  priority: 'warm', outreachAngle: 'Traditional riad near Place Lalla Aouda in Meknes. No contact — underserved city = quick win.',             source: 'Booking.com', notes: 'Near Place Lalla Aouda area.' },
  { name: 'Ryad Bab Berdaine',           type: 'riad', city: 'Meknès',                   email: 'ryadbabberdaine@gmail.com',         website: 'none',  priority: 'hot',  outreachAngle: 'Budget 5-room riad in Meknes medina. Email available — affordable Starter package is the perfect fit.',    source: 'Booking.com', notes: 'Budget-friendly, 5 rooms.' },
  { name: 'Palais Didi',                 type: 'riad', city: 'Meknès',                                                               website: 'none',  priority: 'warm', outreachAngle: 'Budget hostel in Meknes medina. No contact — hostel market needs booking engine, research social media.',   source: 'Booking.com', notes: 'Budget hostel in the medina area.' },
  { name: "Riad La Maison D'a Cote",     type: 'riad', city: 'Meknès',                                                               website: 'none',  priority: 'warm', outreachAngle: 'Traditional guesthouse in Meknes medina. No contact — one of few riads in city = pitch first.',            source: 'Booking.com', notes: 'Traditional guesthouse in the medina.' },
  { name: 'Le Riad Meknes',              type: 'riad', city: 'Meknès',                                                               website: 'none',  priority: 'warm', outreachAngle: 'Budget guesthouse near Meknes medina centre. No contact — find on Booking.com for contact info.',            source: 'Booking.com', notes: 'Budget guesthouse near the medina center.' },
  { name: 'Riad Golden Mansour',         type: 'riad', city: 'Meknès',                                                               website: 'none',  priority: 'warm', outreachAngle: 'Listed on multiple booking platforms — "Golden Mansour" premium name = Pro package is a natural fit.',       source: 'Booking.com', notes: 'Listed on multiple booking platforms.' },

  // ── Rabat Riads ───────────────────────────────────────────────────────────
  { name: 'Riad Asswar',                 type: 'riad', city: 'Rabat',      phone: '+212 6 69 55 05 99',                              website: 'none',  priority: 'hot',  outreachAngle: '8-room Rabat riad near Old Market, highly rated breakfast. Phone — WhatsApp pitch for capital city Starter.', source: 'Booking.com', notes: '8 rooms, near Old Market. Highly rated breakfast.' },
  { name: 'Riad Dar Soufa',              type: 'riad', city: 'Rabat',                                                                website: 'none',  priority: 'warm', outreachAngle: 'Near Kasbah of Udayas with traditional decor. No contact — capital city = diplomatic + business travelers.',  source: 'Booking.com', notes: 'Near Kasbah of the Udayas. Traditional decor.' },
  { name: 'Riad Narjiss',                type: 'riad', city: 'Rabat',                                                                website: 'none',  priority: 'warm', outreachAngle: '5-room Rabat riad 700m from Kasbah of Udayas. No contact — capital city = high-value guests.',               source: 'Booking.com', notes: '5 rooms, near Kasbah of the Udayas (700m).' },
  { name: 'Riad AL Bahi',                type: 'riad', city: 'Rabat',                    email: 'contact@riadalbahi.com',            website: 'basic', priority: 'hot',  outreachAngle: 'Budget centrally-located Rabat riad. Domain email — pitch modern upgrade + direct booking + city guide.',    source: 'Booking.com', notes: 'Budget option, centrally located.' },
  { name: 'Riad Majorelle',              type: 'riad', city: 'Rabat',                                                                website: 'none',  priority: 'warm', outreachAngle: '9-room riad 300m from city centre with sun terrace. No contact — premium name = Pro package pitch.',          source: 'Booking.com', notes: '9 rooms, near city center (300m), sun terrace.' },
  { name: 'Riad Dar Fassi',              type: 'riad', city: 'Rabat',                                                                website: 'none',  priority: 'warm', outreachAngle: 'Traditional riad near Rabat medina. No contact — Fes-style riad in capital = cultural tourism angle.',        source: 'Booking.com', notes: 'Traditional riad near medina center.' },
  { name: 'Riad Roqia',                  type: 'riad', city: 'Rabat',                                                                website: 'none',  priority: 'warm', outreachAngle: '3-room budget riad near Hassan Tower. No contact — UNESCO monument proximity = strong SEO angle.',            source: 'Booking.com', notes: '3 rooms, near Hassan Tower. Budget-friendly.' },
  { name: 'Riad El Wazania',             type: 'riad', city: 'Rabat',                                                                website: 'none',  priority: 'warm', outreachAngle: 'Near Rabat medina souk. No contact — souk proximity = artisan-themed storytelling site pitch.',               source: 'Booking.com', notes: 'Near medina souk area.' },
  { name: 'Riad Razoli Sidi Fateh',      type: 'riad', city: 'Rabat',      phone: '+212 6 65 48 19 66',                              website: 'none',  priority: 'hot',  outreachAngle: 'Traditional Rabat guesthouse near Kasbah. Phone available — WhatsApp pitch for direct booking site.',          source: 'Booking.com', notes: 'Near Kasbah area. Traditional guesthouse.' },
  { name: 'Riad El Maati',               type: 'riad', city: 'Rabat',                    email: 'contact@riadelmaati.com',           website: 'basic', priority: 'hot',  outreachAngle: 'Budget-friendly Rabat medina riad. Domain email — upgrade from basic to professional with booking engine.',   source: 'Booking.com', notes: 'Budget-friendly medina location.' },
  { name: 'Dar Nassiri',                 type: 'riad', city: 'Rabat',                                                                website: 'none',  priority: 'warm', outreachAngle: 'Traditional dar near Souk Sebat in Rabat. No contact — souk location = pitch artisan experience site.',       source: 'Booking.com', notes: 'Near Souk Sebat. Traditional dar.' },
  { name: 'Riad SidiFatah',              type: 'riad', city: 'Rabat',                    email: 'reservation@riadsidifatah.com',     website: 'basic', priority: 'hot',  outreachAngle: 'Has reservation email = already booking-ready. Upgrade basic site with full Stripe checkout + dashboard.',    source: 'Booking.com', notes: 'Named after Sidi Fateh neighborhood.' },
  { name: 'Dar Yanis',                   type: 'riad', city: 'Rabat',                                                                website: 'none',  priority: 'warm', outreachAngle: 'Cozy Rabat medina guesthouse. No contact — find on Booking.com listing for contact details.',                 source: 'Booking.com', notes: 'Cozy guesthouse in the medina.' },
  { name: 'Riad Shama',                  type: 'riad', city: 'Rabat',      phone: '+212 6 93 61 20 79',                              website: 'none',  priority: 'hot',  outreachAngle: 'Rabat riad with phone only. WhatsApp pitch — capital city = diplomatic and business traveler market.',          source: 'Booking.com', notes: 'Phone contact only.' },
  { name: 'Riad El Bir',                 type: 'riad', city: 'Rabat',                    email: 'infos@riadelbir.com',               website: 'basic', priority: 'hot',  outreachAngle: 'Small traditional Rabat riad. Domain email = has basic site — upgrade with full booking flow.',               source: 'Booking.com', notes: 'Small traditional riad.' },
  { name: 'Riad Jbara',                  type: 'riad', city: 'Rabat',                                                                website: 'none',  priority: 'warm', outreachAngle: 'Near Rabat medina quarter. No contact — find via Booking.com listing for contact details.',                   source: 'Booking.com', notes: 'Near medina quarter.' },
  { name: 'Dar Aida',                    type: 'riad', city: 'Rabat',                                                                website: 'none',  priority: 'warm', outreachAngle: 'Traditional family-run Rabat guesthouse. No contact — family business = personal branding site pitch.',         source: 'Booking.com', notes: 'Traditional family-run guesthouse.' },
  { name: 'Riad Boutique Baba',          type: 'riad', city: 'Rabat',                                                                website: 'none',  priority: 'warm', outreachAngle: 'Boutique-style Rabat riad. No contact — boutique brand = premium Pro package is the natural fit.',             source: 'Booking.com', notes: 'Boutique style riad.' },
  { name: 'Ryad Dar Karima',             type: 'riad', city: 'Rabat',                                                                website: 'none',  priority: 'warm', outreachAngle: 'Traditional ryad in old Rabat medina. No contact — historic name = heritage storytelling site pitch.',          source: 'Booking.com', notes: 'Traditional ryad in the old medina.' },
  { name: 'Riad AYA',                    type: 'riad', city: 'Rabat',                                                                website: 'none',  priority: 'warm', outreachAngle: 'Recently listed on Booking.com — brand new. Reach them before they think to build a site themselves.',          source: 'Booking.com', notes: 'Recently listed on Booking.com.' },

  // ── Other Cities ─────────────────────────────────────────────────────────
  { name: 'Riad El Manantial',           type: 'riad', city: 'Tétouan',                                                              website: 'none',  priority: 'warm', outreachAngle: 'Family-friendly riad near Artisanal School in Tetouan UNESCO medina. No contact — cultural tourism pitch.', source: 'Booking.com', notes: 'Near Artisanal School. Family-friendly with terrace.' },
];

// ─── GET /api/leads — list all leads (admin only) ────────────────────────────
router.get('/', protect, authorize('admin'), async (req, res, next) => {
  try {
    const { status, type, priority } = req.query;
    const where = {};
    if (status)   where.status   = status;
    if (type)     where.type     = type;
    if (priority) where.priority = priority;

    const leads = await prisma.lead.findMany({
      where,
      orderBy: [{ priority: 'asc' }, { createdAt: 'desc' }],
    });
    res.json({ success: true, leads });
  } catch (err) { next(err); }
});

// ─── POST /api/leads/import — upsert: adds missing leads, skips existing ──────
router.post('/import', protect, authorize('admin'), async (req, res, next) => {
  try {
    const existing = await prisma.lead.findMany({ select: { name: true } });
    const existingNames = new Set(existing.map(l => l.name));
    const missing = DEFAULT_LEADS.filter(l => !existingNames.has(l.name));

    if (missing.length === 0) {
      const total = await prisma.lead.count();
      return res.json({ success: true, message: `All ${total} leads already imported.`, count: total });
    }

    await prisma.lead.createMany({ data: missing });
    const total = await prisma.lead.count();
    res.json({ success: true, message: `Added ${missing.length} new leads. Total: ${total}.`, count: total });
  } catch (err) { next(err); }
});

// ─── POST /api/leads/sync-contacts — push DEFAULT_LEADS contacts into DB ─────
router.post('/sync-contacts', protect, authorize('admin'), async (req, res, next) => {
  try {
    let updated = 0;
    for (const lead of DEFAULT_LEADS) {
      if (!lead.phone && !lead.email && !lead.instagram) continue;
      const existing = await prisma.lead.findFirst({ where: { name: lead.name } });
      if (!existing) continue;
      const patch = {};
      if (lead.phone     && !existing.phone)     patch.phone     = lead.phone;
      if (lead.email     && !existing.email)     patch.email     = lead.email;
      if (lead.instagram && !existing.instagram) patch.instagram = lead.instagram;
      if (Object.keys(patch).length > 0) {
        await prisma.lead.update({ where: { id: existing.id }, data: patch });
        updated++;
      }
    }
    res.json({ success: true, message: `Updated contact info for ${updated} leads.`, updated });
  } catch (err) { next(err); }
});

// ─── POST /api/leads — create a lead ─────────────────────────────────────────
router.post('/', protect, authorize('admin'), async (req, res, next) => {
  try {
    const { name, type, city, phone, email, instagram, website, priority, outreachAngle, source, notes } = req.body;
    if (!name) return res.status(400).json({ success: false, message: 'Name is required.' });
    const lead = await prisma.lead.create({
      data: { name, type: type || 'riad', city: city || '', phone, email, instagram, website, priority: priority || 'warm', outreachAngle, source, notes },
    });
    res.status(201).json({ success: true, lead });
  } catch (err) { next(err); }
});

// ─── PUT /api/leads/:id — update lead (status, notes, etc.) ──────────────────
router.put('/:id', protect, authorize('admin'), async (req, res, next) => {
  try {
    const { status, notes, priority, email, phone, instagram } = req.body;
    const data = {};
    if (status    !== undefined) data.status    = status;
    if (notes     !== undefined) data.notes     = notes;
    if (priority  !== undefined) data.priority  = priority;
    if (email     !== undefined) data.email     = email;
    if (phone     !== undefined) data.phone     = phone;
    if (instagram !== undefined) data.instagram = instagram;

    const lead = await prisma.lead.update({ where: { id: req.params.id }, data });
    res.json({ success: true, lead });
  } catch (err) { next(err); }
});

// ─── DELETE /api/leads/:id ────────────────────────────────────────────────────
router.delete('/:id', protect, authorize('admin'), async (req, res, next) => {
  try {
    await prisma.lead.delete({ where: { id: req.params.id } });
    res.json({ success: true });
  } catch (err) { next(err); }
});

// ─── POST /api/leads/:id/email — send outreach email ─────────────────────────
router.post('/:id/email', protect, authorize('admin'), async (req, res, next) => {
  try {
    const lead = await prisma.lead.findUnique({ where: { id: req.params.id } });
    if (!lead) return res.status(404).json({ success: false, message: 'Lead not found.' });
    if (!lead.email) return res.status(400).json({ success: false, message: 'This lead has no email address.' });

    const { subject, body } = req.body;
    if (!subject || !body) return res.status(400).json({ success: false, message: 'Subject and body are required.' });

    const result = await sendEmail({ to: lead.email, subject, html: body });

    if (result.sent) {
      await prisma.lead.update({
        where: { id: lead.id },
        data:  { status: 'emailed', emailSentAt: new Date() },
      });
    }

    res.json({ success: result.sent, result });
  } catch (err) { next(err); }
});

// ─── GET /api/leads/templates — return outreach templates ────────────────────
router.get('/templates', protect, authorize('admin'), async (req, res, next) => {
  try {
    const { type = 'riad', name = 'your business' } = req.query;
    const tpl = templates.outreach({ name, type });
    res.json({ success: true, subject: tpl.subject, html: tpl.html });
  } catch (err) { next(err); }
});

module.exports = router;
