import {
  Lightbulb, TrendingUp, Code2, Palette, Shield,
  Rocket, Zap, Globe, ShoppingCart, BarChart3, Smartphone,
} from 'lucide-react';
import type { LucideIcon } from 'lucide-react';

export interface Article {
  slug: string;
  icon: LucideIcon;
  tag: string;
  title: string;
  excerpt: string;
  readTime: string;
  featured: boolean;
  content: string[];
}

export const TAG_COLORS: Record<string, string> = {
  Strategy: '#7c3aed',
  Development: '#3b82f6',
  Design: '#ec4899',
  Growth: '#10b981',
  Security: '#f59e0b',
};

export const ARTICLES: Article[] = [
  {
    slug: 'why-your-business-needs-a-custom-website',
    icon: Lightbulb,
    tag: 'Strategy',
    title: 'Why Your Business Needs a Custom Website in 2025',
    excerpt: 'Template websites can only take you so far. Learn why investing in a custom-built site pays off in performance, SEO, and brand trust.',
    readTime: '5 min read',
    featured: true,
    content: [
      'In 2025, your website is your most important salesperson. It works 24/7, never takes a day off, and is often the first interaction a potential client has with your brand. Yet many businesses still rely on cookie-cutter templates that blend in with thousands of other sites.',
      'The biggest limitation of template websites is performance. Templates are loaded with features you\'ll never use — sliders, plugins, and third-party scripts that bloat your page and slow everything down. A custom-built site includes only what you need, resulting in faster load times and better Core Web Vitals scores.',
      'SEO is another area where custom sites dominate. Search engines reward clean, semantic HTML, fast load times, and structured data. With a custom build, every meta tag, heading hierarchy, and schema markup is intentional. Templates often generate messy markup that confuses crawlers and hurts rankings.',
      'Brand differentiation is perhaps the strongest argument. Your competitors are using the same handful of popular themes. When a potential client visits three similar-looking websites in a row, none of them stand out. A custom design communicates professionalism, attention to detail, and investment in quality.',
      'Security is often overlooked. Popular WordPress themes and plugins are prime targets for hackers because vulnerabilities affect millions of sites simultaneously. A custom-coded site with a modern framework like Next.js has a dramatically smaller attack surface.',
      'The cost argument against custom websites is increasingly weak. Modern frameworks and component libraries mean a skilled developer can build a production-ready custom site in 2-4 weeks — not the 6-month timeline people imagine. The ROI from better conversions, SEO, and brand perception pays for the investment within months.',
      'If your website is the foundation of your digital presence, it should be built specifically for your business — not assembled from parts designed for everyone and optimized for no one.',
    ],
  },
  {
    slug: 'how-fast-website-impacts-revenue',
    icon: TrendingUp,
    tag: 'Growth',
    title: 'How a Fast Website Directly Impacts Your Revenue',
    excerpt: 'Every second of load time costs conversions. We break down the data and show you what to prioritize for maximum speed.',
    readTime: '4 min read',
    featured: true,
    content: [
      'Amazon found that every 100ms of latency cost them 1% in sales. Google discovered that a half-second delay in search results caused a 20% drop in traffic. These aren\'t outliers — they represent a universal truth about how humans interact with the web.',
      'The psychology is simple: speed equals trust. When a page loads instantly, users subconsciously associate that responsiveness with competence and reliability. When it lags, doubt creeps in. "If they can\'t make their website work, can they deliver on their product?"',
      'Core Web Vitals — Google\'s metrics for page experience — now directly influence search rankings. Largest Contentful Paint (LCP) measures how fast your main content appears. First Input Delay (FID) measures interactivity. Cumulative Layout Shift (CLS) measures visual stability. Fail on any of these and Google will rank your competitors above you.',
      'The biggest performance killers are unoptimized images, render-blocking JavaScript, and excessive third-party scripts. A single analytics tag, chat widget, and social media embed can add 500KB+ to your page weight and seconds to your load time.',
      'Modern solutions are straightforward: use Next.js Image component for automatic optimization, lazy-load anything below the fold, implement code splitting so users only download the JavaScript they need, and serve assets from a CDN close to your users.',
      'Server-side rendering (SSR) and static site generation (SSG) eliminate the blank-screen problem entirely. Instead of shipping a JavaScript bundle that builds the page in the browser, you send fully-rendered HTML that displays instantly while JavaScript loads in the background.',
      'The bottom line: a website that loads in under 2 seconds will outperform a 5-second site in every metric that matters — bounce rate, session duration, conversion rate, and search ranking. Speed isn\'t a nice-to-have; it\'s revenue.',
    ],
  },
  {
    slug: 'saas-vs-traditional-web-app',
    icon: Code2,
    tag: 'Development',
    title: 'SaaS vs Traditional Web App: Choosing the Right Architecture',
    excerpt: 'Understand the trade-offs between SaaS platforms and traditional web applications for your next project.',
    readTime: '7 min read',
    featured: false,
    content: [
      'When planning a web application, one of the first architectural decisions is whether to build a traditional single-tenant app or a multi-tenant SaaS platform. The choice affects everything from database design to pricing strategy to how you handle deployments.',
      'A traditional web application serves one client or organization. It has its own database, its own deployment, and can be customized without affecting other users. Think of it as a house — you own everything and can renovate freely.',
      'A SaaS platform serves multiple tenants from a single codebase and often a shared database. It\'s an apartment building — shared infrastructure with individual spaces. This model enables recurring revenue, automatic updates, and economies of scale.',
      'The database question is central. Single-tenant apps can use whatever schema works best. Multi-tenant SaaS must decide between shared databases with tenant IDs (cheaper, harder to isolate), separate schemas per tenant (balanced), or separate databases per tenant (most isolated, most expensive).',
      'Authentication gets more complex with SaaS. You need tenant-aware auth, role management within each tenant, and potentially SSO integration. Traditional apps can get away with simpler user/admin role structures.',
      'Deployment and updates are where SaaS shines. Push once, update everyone. With traditional apps, each client might be on a different version, requiring maintenance windows and migration scripts for each deployment.',
      'Start with the business model: if you\'re solving a problem for one client, build a traditional app. If you\'re building a product for a market, build SaaS. The technical architecture should follow the business strategy, not the other way around.',
    ],
  },
  {
    slug: 'psychology-of-dark-mode',
    icon: Palette,
    tag: 'Design',
    title: 'The Psychology of Dark Mode: Why Users Prefer It',
    excerpt: 'Dark interfaces aren\'t just trendy — they reduce eye strain, save battery, and create a premium feel that builds trust.',
    readTime: '4 min read',
    featured: false,
    content: [
      'Dark mode has gone from a developer preference to a mainstream design standard. Apple, Google, Twitter, and virtually every major platform now offer it — and for most users, it\'s the default. But the reasons behind this shift go deeper than aesthetics.',
      'Eye strain is the most cited benefit. In low-light environments — which is where most evening browsing happens — a bright white screen forces your pupils to contract, causing discomfort. Dark backgrounds with light text reduce the total light emitted, making extended reading sessions more comfortable.',
      'Battery life is a tangible benefit on OLED and AMOLED screens, which power most modern smartphones. These displays light individual pixels, so black pixels are literally off. A dark interface can reduce battery consumption by 30-60% compared to a white interface at full brightness.',
      'The psychological impact is where it gets interesting. Dark interfaces feel premium. Luxury brands — from high-end fashion to premium automotive — have always used dark backgrounds. There\'s a subconscious association between darkness and exclusivity, sophistication, and quality.',
      'Contrast and focus improve with dark mode when done correctly. A dark background eliminates visual noise and makes content — particularly images, videos, and colored elements — pop. UI elements with subtle glows and gradients look dramatically better against dark surfaces.',
      'The key to good dark mode design is avoiding pure black (#000000). It creates too much contrast with white text, causing halation — a glowing effect around letters that strains the eyes. Instead, use dark grays (#0a0a0d to #111115) that feel black but read comfortably.',
      'If your target audience includes professionals, tech-savvy users, or anyone who browses after sunset — which is most people — dark mode isn\'t optional. It\'s expected.',
    ],
  },
  {
    slug: 'web-security-essentials',
    icon: Shield,
    tag: 'Security',
    title: 'Web Security Essentials Every Business Owner Should Know',
    excerpt: 'From HTTPS to JWT tokens — the non-technical guide to keeping your website and customer data safe.',
    readTime: '6 min read',
    featured: false,
    content: [
      'Web security isn\'t just a developer concern — it\'s a business risk. A single breach can cost you customers, reputation, and in some jurisdictions, significant fines. Here\'s what every business owner should understand about keeping their web presence secure.',
      'HTTPS is non-negotiable. It encrypts all data between your users\' browsers and your server. Without it, passwords, credit card numbers, and personal information travel in plain text. Google also marks HTTP sites as "Not Secure" in Chrome, destroying user trust instantly.',
      'Authentication is how you verify users are who they claim to be. Modern applications use JWT (JSON Web Tokens) — encrypted tokens that contain user identity without requiring the server to maintain session state. Always store tokens securely, never in localStorage for sensitive apps, and implement token expiration.',
      'Input validation prevents injection attacks — the most common web vulnerability. Never trust data from users. Every form field, URL parameter, and API input should be validated and sanitized before it touches your database. SQL injection and XSS (cross-site scripting) are still in the top 10 web vulnerabilities because developers skip this step.',
      'Rate limiting protects against brute force attacks and abuse. Without it, an attacker can try thousands of password combinations per minute or overwhelm your API with requests. Implement limits per IP address and per user account.',
      'Keep dependencies updated. Most breaches exploit known vulnerabilities in outdated packages. Run security audits regularly (npm audit, for example) and update dependencies promptly when security patches are released.',
      'Backups are your last line of defense. Automate daily database backups, store them encrypted in a different location than your primary server, and test your restore process quarterly. When everything else fails, a recent backup is the difference between a bad day and a business-ending event.',
    ],
  },
  {
    slug: 'building-website-that-works-worldwide',
    icon: Globe,
    tag: 'Strategy',
    title: 'Going Global: How to Build a Website That Works Worldwide',
    excerpt: 'Multilingual support, RTL layouts, and CDN optimization — everything you need to serve a global audience.',
    readTime: '5 min read',
    featured: false,
    content: [
      'Expanding your website to serve a global audience involves more than just translating text. It requires rethinking layout, performance, content strategy, and user expectations across cultures.',
      'Internationalization (i18n) starts with separating text from code. Every string visible to users should come from a translation file, not be hardcoded in components. This includes button labels, error messages, date formats, currency symbols, and even pluralization rules — "1 item" vs "2 items" works differently across languages.',
      'Right-to-left (RTL) support is essential if you\'re targeting Arabic, Hebrew, Farsi, or Urdu speakers. This isn\'t just mirroring text — your entire layout flips. Navigation moves to the right, progress bars fill from right to left, and icons like arrows reverse direction. CSS logical properties (margin-inline-start instead of margin-left) make this manageable.',
      'Performance varies dramatically by region. Users in Morocco, Southeast Asia, or Sub-Saharan Africa often browse on slower connections and less powerful devices. Optimize aggressively: compress images, minimize JavaScript, use a CDN with edge locations near your target markets, and test on 3G connections.',
      'Cultural considerations affect design decisions. Color meanings vary — red signals luck in China but danger in Western cultures. Imagery should reflect your audience. Date formats differ (DD/MM/YYYY vs MM/DD/YYYY). Even the length of translated text varies dramatically — German words are often 30% longer than English equivalents, breaking fixed-width layouts.',
      'SEO for international audiences requires hreflang tags that tell search engines which version of your page to show to users in each locale. Without them, Google might show your French page to English speakers or vice versa.',
      'Start with your primary market, build the i18n infrastructure properly from day one, then add languages incrementally. Retrofitting internationalization into an existing codebase is ten times harder than building it in from the start.',
    ],
  },
  {
    slug: 'ecommerce-mistakes-killing-conversions',
    icon: ShoppingCart,
    tag: 'Growth',
    title: '7 E-Commerce Mistakes That Kill Your Conversion Rate',
    excerpt: 'From slow checkout flows to missing trust signals — the common pitfalls we see and how to fix them fast.',
    readTime: '6 min read',
    featured: false,
    content: [
      'Most e-commerce sites lose customers not because of their products but because of friction in the buying experience. Here are the seven mistakes we see most often and how to fix them.',
      'Mistake 1: Requiring account creation before checkout. 24% of shoppers abandon carts when forced to create an account. Always offer guest checkout. Collect the email for order updates, then invite them to create an account after the purchase is complete.',
      'Mistake 2: Hidden shipping costs. Unexpected fees at checkout are the #1 reason for cart abandonment (48% of cases). Show shipping estimates on product pages, offer free shipping thresholds ("Free shipping on orders over $50"), and be transparent about delivery times.',
      'Mistake 3: Slow page loads. If your product page takes more than 3 seconds to load, you lose 53% of mobile visitors before they even see your product. Optimize images, implement lazy loading, and cache aggressively.',
      'Mistake 4: Poor mobile experience. Over 60% of e-commerce traffic is mobile, but many stores still treat mobile as an afterthought. Tap targets should be at least 44px, forms should use appropriate keyboard types (numeric for credit cards), and the checkout flow should be completable with a thumb.',
      'Mistake 5: Missing trust signals. New visitors need reassurance. Display security badges near payment forms, show customer reviews prominently, include a clear return policy, and make your contact information easy to find. Trust is built through transparency.',
      'Mistake 6: Complicated navigation. If customers can\'t find what they want in 3 clicks, they leave. Implement clear categories, a prominent search bar with autocomplete, and breadcrumb navigation. Use filters that actually work — by price, size, color, rating.',
      'Mistake 7: No urgency or social proof. "Only 3 left in stock," "24 people viewing this," and "Ordered 12 times today" are powerful conversion drivers when used honestly. Combine with limited-time offers and you create the gentle push that turns browsers into buyers.',
    ],
  },
  {
    slug: 'nextjs-vs-react-spa',
    icon: Rocket,
    tag: 'Development',
    title: 'Next.js vs React SPA: Which One Should You Choose?',
    excerpt: 'Server-side rendering, static generation, and API routes — when Next.js is the right choice and when it isn\'t.',
    readTime: '8 min read',
    featured: false,
    content: [
      'React gives you a library for building user interfaces. Next.js gives you a framework built on React that handles routing, rendering, optimization, and deployment. The question isn\'t which is better — it\'s which is right for your project.',
      'A React SPA (Single Page Application) loads one HTML file, then JavaScript takes over to render everything in the browser. This is called Client-Side Rendering (CSR). It works great for apps behind a login — dashboards, admin panels, internal tools — where SEO doesn\'t matter and the initial load is a one-time cost.',
      'Next.js adds Server-Side Rendering (SSR) and Static Site Generation (SSG). With SSR, the server renders HTML for each request, so users and search engines see content immediately. With SSG, pages are pre-built at deploy time, served from a CDN, and load almost instantly.',
      'For SEO-dependent sites — marketing pages, blogs, e-commerce — Next.js is the clear winner. Search engines can crawl server-rendered pages immediately, while SPAs require JavaScript execution that some crawlers handle poorly or skip entirely.',
      'Next.js App Router (v13+) introduced React Server Components, which render on the server and send zero JavaScript to the client. This means your product listing page can fetch data, render HTML, and deliver it without any client-side JS overhead. Only interactive elements (buttons, forms) need client-side code.',
      'API Routes in Next.js let you build backend endpoints alongside your frontend. For simple backends — form submissions, database queries, third-party API proxies — you can skip building a separate Express server entirely. For complex backends with real-time features, WebSockets, or heavy processing, a dedicated backend still makes sense.',
      'Performance comparison: a well-built Next.js site will have a faster First Contentful Paint (FCP) and Largest Contentful Paint (LCP) than an equivalent SPA. The SPA may feel snappier on subsequent navigations since it doesn\'t need full page reloads, but Next.js prefetching largely closes this gap.',
      'Our recommendation: use Next.js for anything public-facing where SEO, performance, and initial load time matter. Use a React SPA for authenticated apps where the user is already committed and the priority is rich interactivity after login. Many projects use both — Next.js for the marketing site and a SPA for the dashboard.',
    ],
  },
  {
    slug: 'mobile-first-design-beyond-screen-size',
    icon: Smartphone,
    tag: 'Design',
    title: 'Mobile-First Design: It\'s Not Just About Screen Size',
    excerpt: 'Touch targets, gesture navigation, safe areas, and performance budgets — designing for mobile properly.',
    readTime: '5 min read',
    featured: false,
    content: [
      'Mobile-first design is often reduced to "make it responsive" — stack columns on small screens, shrink fonts, hide the sidebar. But true mobile-first thinking goes much deeper. It\'s about designing for how people actually use phones.',
      'Touch targets must be at least 44x44 pixels (Apple\'s guideline) or 48x48 dp (Google\'s). Anything smaller and users will mis-tap, especially on crowded interfaces. This means your nav links, buttons, and form elements need generous padding. "It looks fine on my monitor" is not a valid test.',
      'Thumb zones matter. On a modern phone held one-handed, the comfortable reach area is the bottom-center of the screen. Primary actions should live there. That\'s why bottom navigation bars dominate mobile design — they put the most-used controls where thumbs naturally rest.',
      'Gesture navigation is now standard. Users expect to swipe back, pull to refresh, and swipe between tabs. Your interface should support these patterns without conflicting with the OS-level gestures. A horizontal carousel that fights with the back swipe will frustrate users instantly.',
      'Safe areas are the regions of the screen not covered by the notch, Dynamic Island, home indicator, or rounded corners. Content that extends into these areas gets clipped or obscured. Use CSS env(safe-area-inset-top/bottom/left/right) to respect device boundaries.',
      'Performance budgets are stricter on mobile. Mobile processors are 3-5x slower than desktop CPUs. Mobile connections are often 4G or spotty WiFi. Your JavaScript bundle, image weights, and animation complexity all need to be lighter. Target under 200KB of JavaScript for the initial page load.',
      'Test on real devices. Simulators miss touch responsiveness, real-world network conditions, and the physical experience of holding a phone. Borrow devices from friends, use BrowserStack, or at minimum test on both iOS Safari and Android Chrome — they render and behave differently in subtle but important ways.',
    ],
  },
  {
    slug: 'seo-2025-what-moves-the-needle',
    icon: BarChart3,
    tag: 'Growth',
    title: 'SEO in 2025: What Actually Moves the Needle',
    excerpt: 'Core Web Vitals, structured data, and content authority — the SEO strategies that matter now.',
    readTime: '7 min read',
    featured: false,
    content: [
      'SEO in 2025 is less about tricks and more about fundamentals done exceptionally well. Google\'s algorithms have matured to the point where the best strategy is simply building a great website with genuinely useful content.',
      'Core Web Vitals are now a confirmed ranking signal. LCP (Largest Contentful Paint) should be under 2.5 seconds, FID (First Input Delay) under 100ms, and CLS (Cumulative Layout Shift) under 0.1. These aren\'t abstract metrics — they directly measure what users experience. Tools like PageSpeed Insights and Lighthouse give you specific, actionable recommendations.',
      'Structured data (Schema.org markup) helps Google understand your content and display rich results — star ratings, prices, FAQ dropdowns, breadcrumbs, and event dates directly in search results. Pages with rich results get significantly higher click-through rates. Implement Organization, Product, FAQ, and Article schemas where applicable.',
      'Content authority beats content volume. Google\'s Helpful Content Update penalizes sites that publish large amounts of generic, AI-generated filler. Instead, publish fewer pieces that demonstrate genuine expertise, cite original data, and provide actionable advice. One authoritative article outranks twenty thin ones.',
      'Internal linking is the most underused SEO lever. Every page on your site should link to related pages with descriptive anchor text. This helps Google discover and understand your content hierarchy, and distributes page authority throughout your site. Build topic clusters — a pillar page linked to supporting articles.',
      'Technical SEO still matters. Ensure your sitemap is current, robots.txt isn\'t blocking important pages, canonical URLs are set correctly, and your site renders properly without JavaScript (or use SSR/SSG). Check for crawl errors in Google Search Console weekly.',
      'Local SEO is critical for service businesses. Claim your Google Business Profile, ensure your name/address/phone are consistent across directories, collect genuine reviews, and create location-specific content. For businesses serving specific regions, local SEO often delivers faster results than competing nationally.',
    ],
  },
  {
    slug: 'realtime-features-sse-websockets-polling',
    icon: Zap,
    tag: 'Development',
    title: 'Real-Time Features: SSE, WebSockets, or Polling?',
    excerpt: 'Compare the three main approaches to real-time data and learn which one fits your use case best.',
    readTime: '6 min read',
    featured: false,
    content: [
      'Real-time features — live notifications, chat, collaborative editing, live dashboards — are no longer nice-to-haves. Users expect instant updates. The question is which technology to use: Server-Sent Events (SSE), WebSockets, or plain polling.',
      'Polling is the simplest approach. Your client sends a request to the server every N seconds asking "anything new?" It\'s easy to implement, works everywhere, and uses standard HTTP. The downside: it\'s wasteful. Most requests return nothing, burning bandwidth and server resources. Use polling only when updates are infrequent (every 30+ seconds) and simplicity outweighs efficiency.',
      'Server-Sent Events (SSE) establish a one-way stream from server to client over a standard HTTP connection. The server pushes updates whenever they happen — no wasted requests. SSE handles reconnection automatically, works through most proxies and firewalls, and uses simple text-based messages. The limitation: it\'s one-directional. The client can\'t send data back through the same connection.',
      'WebSockets create a full-duplex, bidirectional connection between client and server. Both sides can send messages at any time. This is ideal for chat applications, multiplayer games, or collaborative editors where both parties need to send data frequently. The cost: more complex server infrastructure, potential issues with load balancers and proxies, and manual reconnection logic.',
      'For most business applications — notifications, activity feeds, live status updates, dashboard refreshes — SSE is the sweet spot. It\'s simpler than WebSockets, more efficient than polling, and handles 90% of real-time use cases. We use SSE in our own platform for project updates, message notifications, and payment status changes.',
      'Scaling considerations: SSE and WebSockets both maintain persistent connections, which consumes server memory. A single Node.js server can handle 10,000-50,000 concurrent connections comfortably. Beyond that, you need Redis pub/sub or a similar message broker to coordinate across multiple server instances.',
      'Choose polling for simplicity on non-critical features, SSE for server-to-client push (most cases), and WebSockets only when you need bidirectional real-time communication. Start with the simplest solution that meets your requirements — you can always upgrade later.',
    ],
  },
  {
    slug: 'gdpr-privacy-website-requirements',
    icon: Shield,
    tag: 'Security',
    title: 'GDPR & Privacy: What Your Website Must Have',
    excerpt: 'Cookie consent, data handling, and user rights — the legal requirements every modern website needs to meet.',
    readTime: '5 min read',
    featured: false,
    content: [
      'GDPR (General Data Protection Regulation) affects any website that serves users in the European Union — regardless of where your business is located. Non-compliance can result in fines up to 4% of global annual revenue. Here\'s what your website actually needs.',
      'Cookie consent must be informed and granular. A banner that says "We use cookies" with only an "Accept" button is not compliant. Users must be able to accept, reject, or choose which categories of cookies to allow (necessary, analytics, marketing). Don\'t load tracking scripts until consent is given — this means your Google Analytics, Facebook Pixel, and chat widgets should only fire after explicit opt-in.',
      'Your privacy policy must be clear, specific, and accessible. It should explain what data you collect, why you collect it, how long you store it, who you share it with, and how users can request deletion. Generic templates are better than nothing, but a policy tailored to your actual data practices is what the regulation requires.',
      'Right to access and right to deletion are user rights you must support. If a user asks "what data do you have on me?" you must be able to answer within 30 days. If they ask you to delete their data, you must comply (with limited exceptions). This means your database needs to support data export and deletion workflows.',
      'Data minimization means only collecting what you actually need. Don\'t require a phone number if you\'ll never call. Don\'t collect a date of birth if you don\'t need age verification. Every field in your forms should have a clear business justification.',
      'Third-party services are your responsibility too. If you use Google Analytics, Stripe, Mailchimp, or any SaaS tool that processes user data, your privacy policy must disclose this. Ensure these services have their own GDPR-compliant data processing agreements in place.',
      'Practical first steps: install a proper cookie consent manager (like Cookiebot or a custom solution), audit your data collection points, write a real privacy policy, add a data deletion flow to your user settings, and ensure your forms only collect what\'s necessary. It\'s not as overwhelming as it sounds — start with the basics and iterate.',
    ],
  },
];

export function getArticleBySlug(slug: string): Article | undefined {
  return ARTICLES.find(a => a.slug === slug);
}
